"""ControlNet pair pilot (research/controlnet-pair-pilot.md): both members of a pedestrian pair are generated by
Cosmos-Transfer2.5 from the SAME real WOD clip's controls, x+ with the target pedestrian in the controls and x- with it
removed from them, same prompt and seed, so generator artifacts are symmetric and the pair differs by the pedestrian.

Clips: the 19 P3 pedestrian-deletion scenes (processed/nq4_p3/scenes/p3_XXX, target_track), front camera from
drivestudio's processed WOD (processed/waymo_ds/training/<scene>), 93 frames at the log's 10 Hz, cropped to 16:9 and
resized to 1280 x 704. Everything lives under $DATA_DIR/runs/cn_pair/.

  prep     (envs/ultralytics, GPU) window with the most frames of the target in view; target pixels = the YOLO26x-seg
           person mask matched to the projected 3-D box (projected hull when no detection matches); removal region =
           mask dilated; clean plate = big-lama inside the region per frame; canny edges of both
  specs    Cosmos spec (jsonl) for an arm and a scene list (scripts/cosmos_infer.py runs it)
  anchor   an arm's x- as lossless mp4, anchor of a guided x+ ; blend: feathered paste of a guided x+ into x-
  insert   walking CARLA pedestrian (P5 v1 clips of the Cosmos pilot) pasted into the x- controls along a kerb-to-lane path
  webp     real | x+ | x- review clip per (scene, arm) -> runs/cn_pair/figs/ (pulled to research/figs/cn_pair/)
"""
import json
from pathlib import Path

import numpy as np

from .common import data_dir, get_logger
from .cosmos_pilot import write_mp4

log = get_logger(__name__)
REPO = Path(__file__).resolve().parents[1]
W, H, T, FPS = 1280, 704, 93, 10
SRC_W, CROP_Y0 = 1920, 150                          # 1920 x 1280 -> rows [150, 1206) -> 1280 x 704 (x 2/3)
S = W / SRC_W
SEED = 2025
CANNY = (100, 200)                                  # Cosmos preset "medium"
DIL_MASK, DIL_HULL = 10, 4                          # removal region: mask / box hull dilation, px at 1280
FREE_DIL, FREE_T = 24, 3                            # guided free region: region dilated, +-3 frames
SCENES = [f"p3_{i:03d}" for i in range(19)]


def out(*p) -> Path:
    d = data_dir() / "runs" / "cn_pair" / Path(*p)
    d.mkdir(parents=True, exist_ok=True)
    return d


def pack(a):
    return np.packbits(a.reshape(len(a), -1), axis=1)


def unpack(a):
    return np.unpackbits(a, axis=1)[:, :H * W].reshape(-1, H, W).astype(bool)


# ------------------------------------------------------------------ geometry (drivestudio processed WOD)

def _cam(sd: Path, t: int):
    ego = np.loadtxt(sd / "ego_pose" / f"{t:03d}.txt")
    c2e = np.loadtxt(sd / "extrinsics" / "0.txt")
    fx, fy, cx, cy, k1, k2, p1, p2, k3 = np.loadtxt(sd / "intrinsics" / "0.txt")
    return np.linalg.inv(ego @ c2e), np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]]), np.array([k1, k2, p1, p2, k3])


def project(pts_w: np.ndarray, cam) -> tuple[np.ndarray, np.ndarray]:
    """World points -> (u, v) in the 1280 x 704 crop and camera depth (m). Waymo camera frame: x fwd, y left, z up."""
    import cv2
    w2c, K, dist = cam
    p = pts_w @ w2c[:3, :3].T + w2c[:3, 3]
    cv = np.stack([-p[:, 1], -p[:, 2], p[:, 0]], 1)
    z = cv[:, 2].copy()
    uv, _ = cv2.projectPoints(np.where(z[:, None] > 0.1, cv, np.array([0, 0, 1.0])), np.zeros(3), np.zeros(3), K, dist)
    uv = uv[:, 0] * S - np.array([0, CROP_Y0 * S])
    return uv, z


def box_corners(o2w: np.ndarray, size) -> np.ndarray:
    l, w, h = size
    c = np.array([[sx * l / 2, sy * w / 2, sz * h / 2, 1] for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)])
    return (c @ np.asarray(o2w).T)[:, :3]


def _instances(sd: Path) -> dict:
    info = json.loads((sd / "instances" / "instances_info.json").read_text())
    return {v["id"]: v for v in info.values()}


def _hull(uv: np.ndarray) -> np.ndarray:
    import cv2
    m = np.zeros((H, W), np.uint8)
    cv2.fillConvexPoly(m, cv2.convexHull(np.round(uv).astype(np.int32)), 1)
    return m > 0


# ------------------------------------------------------------------ prep (envs/ultralytics)

def _target_track(sd: Path, tid: str, n: int):
    inst = _instances(sd)[tid]
    fa = inst["frame_annotations"]
    boxes = {}
    for f, o2w, sz in zip(fa["frame_idx"], fa["obj_to_world"], fa["box_size"]):
        if f >= n:
            continue
        uv, z = project(box_corners(o2w, sz), _cam(sd, f))
        if (z > 0.5).all():
            x0, y0, x1, y1 = uv[:, 0].min(), uv[:, 1].min(), uv[:, 0].max(), uv[:, 1].max()
            ix0, iy0, ix1, iy1 = max(x0, 0), max(y0, 0), min(x1, W), min(y1, H)
            if ix1 - ix0 > 3 and iy1 - iy0 > 12:
                boxes[f] = {"uv": uv, "box": (x0, y0, x1, y1), "dist": float(np.linalg.norm(np.asarray(o2w)[:3, 3] -
                            np.linalg.inv(_cam(sd, f)[0])[:3, 3])), "h_px": float(y1 - y0)}
    return boxes


def _window(boxes: dict, n: int, f0: int) -> int:
    vis = np.zeros(n, bool)
    vis[[f for f, b in boxes.items() if b["h_px"] >= 20]] = True
    best = max(range(max(n - T, 0) + 1), key=lambda s: (vis[s:s + T].sum(), -abs(s + T // 2 - f0)))
    return best


def _load(sd: Path, f: int) -> np.ndarray:
    import cv2
    im = cv2.imread(str(sd / "images" / f"{f:03d}_0.jpg"))[..., ::-1]
    im = im[CROP_Y0:CROP_Y0 + int(round(H / S))]
    return cv2.resize(im, (W, H), interpolation=cv2.INTER_AREA)


def prep(scenes: list[str]):
    import cv2
    import torch
    from ultralytics import YOLO
    from .elicit_e2 import Lama, _match, _iou
    yolo = YOLO(str(data_dir() / "models" / "ultralytics" / "yolo26x-seg.pt"))
    lama = Lama()
    for key in scenes:
        d = out("clips", key)
        if (d / "prep.json").exists():
            continue
        m = json.loads((data_dir() / "processed/nq4_p3/scenes" / key / "meta.json").read_text())
        sd = data_dir() / "processed/waymo_ds/training" / f"{m['scene']:03d}"
        n = len(list((sd / "images").glob("*_0.jpg")))
        boxes = _target_track(sd, m["target_track"], n)
        s = _window(boxes, n, m["f0"])
        frames = list(range(s, min(s + T, n)))
        assert len(frames) == T, (key, n, s)
        rgb = np.stack([_load(sd, f) for f in frames])
        tmask = np.zeros((T, H, W), bool)
        region = np.zeros((T, H, W), bool)
        src = []
        k_m, k_h = np.ones((2 * DIL_MASK + 1,) * 2, np.uint8), np.ones((2 * DIL_HULL + 1,) * 2, np.uint8)
        for i, f in enumerate(frames):
            b = boxes.get(f)
            if b is None:
                src.append("none")
                continue
            r = yolo.predict(rgb[i][..., ::-1], imgsz=1280, conf=0.15, classes=[0], retina_masks=True, half=True,
                             verbose=False)[0]
            best, bi = None, 0.0
            if r.masks is not None:
                for j, db in enumerate(r.boxes.xyxy.cpu().numpy()):
                    if _match(db, b["box"]) and _iou(db, b["box"]) >= bi:
                        best, bi = j, _iou(db, b["box"])
            hull = _hull(b["uv"])
            if best is not None:
                mk = r.masks.data[best].cpu().numpy() > 0.5
                tmask[i] = mk
                region[i] = cv2.dilate(mk.astype(np.uint8), k_m) > 0
                src.append("yolo")
            else:
                tmask[i] = hull
                region[i] = cv2.dilate(hull.astype(np.uint8), k_h) > 0
                src.append("hull")
        clean = rgb.copy()
        for i in range(T):
            if region[i].any():
                img = torch.from_numpy(rgb[i]).permute(2, 0, 1).cuda()
                clean[i] = lama(img, torch.from_numpy(region[i]).cuda()).permute(1, 2, 0).cpu().numpy()
        np.savez_compressed(d / "clip.npz", tmask=pack(tmask), region=pack(region))
        np.save(d / "rgb.npy", rgb)
        np.save(d / "clean.npy", clean)
        write_mp4(d / "real.mp4", rgb, fps=FPS)
        write_mp4(d / "clean.mp4", clean, fps=FPS)
        _edges(d, rgb, clean, region)
        fi = json.loads((sd / "frame_info.json").read_text()) if (sd / "frame_info.json").exists() else {}
        px = tmask.reshape(T, -1).sum(1)
        info = {"key": key, "segment": m["segment"], "wds_scene": m["scene"], "target": m["target_track"], "f0": m["f0"],
                "start": s, "frames": frames, "src": src, "px": px.tolist(), "frame_info": fi,
                "dist": [boxes[f]["dist"] if f in boxes else None for f in frames],
                "n_vis": int((px >= 300).sum()), "n_yolo": src.count("yolo"), "n_hull": src.count("hull")}
        (d / "prep.json").write_text(json.dumps(info))
        log.info("%s: window %d-%d, target >= 300 px in %d frames (yolo %d, hull %d), min dist %.1f m", key, s,
                 s + T - 1, info["n_vis"], info["n_yolo"], info["n_hull"],
                 min([x for x in info["dist"] if x is not None], default=float("nan")))


def _edges(d: Path, rgb, clean, region):
    """edge_plus = canny of the real frames; edge_minus = the same outside the region, canny of the clean plate inside
    (a kerb or lane line behind the pedestrian continues); edge_drop = no edges inside the region."""
    import cv2
    ep = np.stack([cv2.Canny(cv2.cvtColor(x, cv2.COLOR_RGB2GRAY), *CANNY) > 0 for x in rgb])
    ec = np.stack([cv2.Canny(cv2.cvtColor(x, cv2.COLOR_RGB2GRAY), *CANNY) > 0 for x in clean])
    em = np.where(region, ec, ep)
    ed = ep & ~region
    for name, e in (("edge_plus", ep), ("edge_minus", em), ("edge_drop", ed)):
        write_mp4(d / f"{name}.mp4", np.repeat((e * 255).astype(np.uint8)[..., None], 3, -1), fps=FPS)
    import cv2 as _c
    k = np.ones((2 * FREE_DIL + 1,) * 2, np.uint8)
    r = np.stack([_c.dilate(x.astype(np.uint8), k) > 0 for x in region])
    free = np.stack([r[max(0, t - FREE_T):t + FREE_T + 1].any(0) for t in range(T)])
    write_mp4(d / "anchor_mask.mp4", np.repeat(((~free) * 255).astype(np.uint8)[..., None], 3, -1), fps=FPS)
    alpha = np.stack([np.maximum(_c.GaussianBlur((_c.dilate(x.astype(np.uint8), np.ones((13, 13), np.uint8)) > 0)
                                                 .astype(np.float32), (0, 0), 4.0), x.astype(np.float32)) for x in region])
    np.save(d / "alpha.npy", alpha.astype(np.float16))


# ------------------------------------------------------------------ specs

def prompt(fi: dict) -> str:
    place = {"location_sf": "a street in San Francisco", "location_phx": "a suburban street in Phoenix",
             "location_other": "a city street"}.get(fi.get("location"), "a city street")
    when = {"Night": "at night, lit by street lamps", "Dawn/Dusk": "at dusk"}.get(fi.get("time_of_day"), "in daylight")
    wx = {"rain": " in the rain, with a wet road surface"}.get(fi.get("weather"), "")
    return (f"A realistic video from a camera mounted on the roof of a car driving on {place} {when}{wx}. The camera is "
            "outside the car, so the view shows only the street ahead, and the road surface reaches the bottom edge "
            "of the frame. Cars, buildings, trees, poles, signs and road markings look like real-world footage, "
            "with natural colours, lighting and textures.")


NEG = ("The video is recorded from inside a car: dashboard, windshield glass, reflections on the glass, wipers, the "
       "hood of the car, car interior. White mannequins, blank white silhouettes, ghostly transparent people. "
       "Cartoonish frames, fake lighting, raw and basic textures, primitive geometries, blur, flicker.")

# name: (model, steps, {control: (plus file, minus file, weight)}, anchored-on arm or None)
ARMS = {
    "E": ("edge/distilled", 4, {"edge": ("edge_plus.mp4", "edge_minus.mp4", 1.0)}, None),
    "Ed": ("edge/distilled", 4, {"edge": ("edge_plus.mp4", "edge_drop.mp4", 1.0)}, None),
    "EG": ("edge/distilled", 4, {"edge": ("edge_plus.mp4", "edge_minus.mp4", 1.0)}, "E"),
    # base 35 steps, edge + vis (Cosmos blurs the input video on the fly: real for x+, clean plate for x-)
    "BV": ("edge", 35, {"edge": ("edge_plus.mp4", "edge_minus.mp4", 1.0), "vis": (None, None, 0.5)}, None),
    "B": ("edge", 35, {"edge": ("edge_plus.mp4", "edge_minus.mp4", 1.0)}, None),
}


def specs(arm: str, scenes: list[str], members: str = "plus,minus", tag: str = "") -> Path:
    model, steps, ctrls, anchored = ARMS[arm]
    lines = []
    for key in scenes:
        d = out("clips", key)
        fi = json.loads((d / "prep.json").read_text())["frame_info"]
        jobs = ["plus"] if anchored else members.split(",")
        for mem in jobs:
            x = {"name": f"{key}_{mem}_{arm}", "prompt": prompt(fi), "seed": SEED, "num_steps": steps, "guidance": 3,
                 "video_path": str(d / ("real.mp4" if mem == "plus" else "clean.mp4"))}
            if model != "edge/distilled":
                x["negative_prompt"] = NEG
            for c, (fp, fm, wgt) in ctrls.items():
                f = fp if mem == "plus" else fm
                x[c] = {"control_weight": wgt} | ({"control_path": str(d / f)} if f else {})
            if anchored:
                x["video_path"] = str(out("anchor") / f"{key}_{anchored}.mp4")
                x["guided_generation_mask"] = str(d / "anchor_mask.mp4")
                x["guided_generation_step_threshold"] = 99
            lines.append(x)
    f = out("specs") / f"{arm}{tag}.jsonl"
    f.write_text("".join(json.dumps(x) + "\n" for x in lines))
    log.info("%d samples -> %s", len(lines), f)
    return f


def anchor(arm: str, scenes: list[str]):
    for key in scenes:
        write_mp4(out("anchor") / f"{key}_{arm}.mp4", np.load(out("gen", arm) / f"{key}_minus_{arm}.npy"), fps=FPS)


def blend(arm: str, base: str, scenes: list[str]):
    """Guided x+ -> feathered paste into the base arm's x- (outside the alpha support x+ == x- exactly)."""
    dst = out("gen", arm + "b")
    for key in scenes:
        a = np.load(out("clips", key) / "alpha.npy").astype(np.float32)[..., None]
        g = np.load(out("gen", arm) / f"{key}_plus_{arm}.npy").astype(np.float32)
        neg = np.load(out("gen", base) / f"{key}_minus_{base}.npy")
        np.save(dst / f"{key}_plus_{arm}b.npy", np.rint(a * g + (1 - a) * neg).astype(np.uint8))
        link = dst / f"{key}_minus_{arm}b.npy"
        link.unlink(missing_ok=True)
        link.symlink_to(out("gen", base) / f"{key}_minus_{base}.npy")


# ------------------------------------------------------------------ review clips

def _font(size):
    from PIL import ImageFont
    for p in ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              str(data_dir() / "envs/drivestudio/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf")):
        if Path(p).exists():
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def webp(arm: str, scenes: list[str], step: int = 2, pw: int = 560):
    """real (target outlined) | x+ | x- , every `step`-th frame, 10 / step fps, caption with scene / arm / frame."""
    import cv2
    from PIL import Image, ImageDraw
    ph = round(pw * H / W)
    f1, f2 = _font(16), _font(13)
    figs = out("figs")
    rows = []
    for key in scenes:
        d = out("clips", key)
        gp, gm = out("gen", arm) / f"{key}_plus_{arm}.npy", out("gen", arm) / f"{key}_minus_{arm}.npy"
        if not (gp.exists() and gm.exists()):
            continue
        rgb, P, M = np.load(d / "rgb.npy"), np.load(gp), np.load(gm)
        reg = unpack(np.load(d / "clip.npz")["region"])
        info = json.loads((d / "prep.json").read_text())
        frames = []
        for t in range(0, T, step):
            r = rgb[t].copy()
            cs, _ = cv2.findContours(reg[t].astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            cv2.drawContours(r, cs, -1, (255, 220, 0), 3)
            G = Image.new("RGB", (3 * pw, ph + 26), (18, 18, 18))
            for k, (im, lab) in enumerate(((r, "real (target outlined)"), (P[t], "x+ (target in controls)"),
                                           (M[t], "x- (target removed from controls)"))):
                G.paste(Image.fromarray(im).resize((pw, ph), Image.LANCZOS), (k * pw, 0))
                ImageDraw.Draw(G).text((k * pw + 6, 4), lab, fill=(255, 255, 255), font=f1, stroke_width=2,
                                       stroke_fill=(0, 0, 0))
            ImageDraw.Draw(G).text((8, ph + 5), f"{key}  arm {arm}  frame {t:02d}/{T - 1}  (log frame {info['start'] + t}, "
                                   f"10 Hz)", fill=(220, 220, 220), font=f2)
            frames.append(G)
        p = figs / f"{key}_{arm}.webp"
        frames[0].save(p, save_all=True, append_images=frames[1:], duration=int(100 * step), loop=0, quality=60,
                       method=6)
        rows.append({"key": key, "arm": arm, "file": p.name, "kb": p.stat().st_size // 1024})
        log.info("%s %s -> %s (%d KB)", key, arm, p.name, p.stat().st_size // 1024)
    return rows


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("step", choices=("prep", "specs", "anchor", "blend", "webp"))
    ap.add_argument("--scenes", default="p3_000")
    ap.add_argument("--arm", default="E")
    ap.add_argument("--base", default="E")
    ap.add_argument("--members", default="plus,minus")
    ap.add_argument("--tag", default="")
    a = ap.parse_args()
    sc = SCENES if a.scenes == "all" else a.scenes.split(",")
    if a.step == "prep":
        prep(sc)
    elif a.step == "specs":
        print(specs(a.arm, sc, a.members, a.tag))
    elif a.step == "anchor":
        anchor(a.arm, sc)
    elif a.step == "blend":
        blend(a.arm, a.base, sc)
    else:
        webp(a.arm, sc)


if __name__ == "__main__":
    main()
