#!/usr/bin/env python3
"""Review section of research/controlnet-pair-pilot.md from research/results/cn_pair/pairs.json (pulled from the box,
written by `jevdrive.cn_pair summary`). Replaces everything below the REVIEW marker; keeps any verdict already filled in.

  python3 scripts/cn_pair_md.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOC = REPO / "research" / "controlnet-pair-pilot.md"
MARK = "<!-- REVIEW: generated by scripts/cn_pair_md.py below this line -->"
VERDICT = "**结论（用户填）：**"
ARMS = {
    "E": ("移除 · E（主设置）", "Edge Distilled 4 步；x⁺ 控制 = 真实帧 Canny；x⁻ 控制 = 区域外与 x⁺ 逐像素相同，区域内换成 LaMa clean plate 的 Canny；两边同 prompt、同 seed、各自独立生成"),
    "Ed": ("移除 · Ed（对照：区域内不给边）", "同 E，但 x⁻ 的区域内边缘直接清空，不用 clean plate 补"),
    "EGb": ("移除 · EG（x⁺ 锚定在 x⁻ 上）", "x⁻ 即 E 的 x⁻；x⁺ 用 x⁺ 的边缘重新生成，区域（膨胀 24 px、±3 帧）以外的 latent 每一步钉在 x⁻ 上，再羽化贴回 x⁻：区域外 x⁺ 与 x⁻ 逐像素相同，不再对称"),
    "BV": ("移除 · BV（base 35 步，edge + vis）", "base 模型 35 步、CFG 3，edge 1.0 + vis 0.5（vis = Cosmos 对输入视频现算的模糊图：x⁺ 用真实视频，x⁻ 用 clean plate），带 negative prompt"),
    "EI": ("插入 · EI（主设置）", "x⁻ 即 E 的 x⁻；x⁺ 控制 = x⁻ 的边缘 + CARLA 行走行人的 Canny（按投影缩放、被更近的场景深度遮挡），同 prompt、同 seed"),
    "EIGb": ("插入 · EIG（x⁺ 锚定在 x⁻ 上）", "同 EI，但 x⁺ 只在行人区域（膨胀 24 px、±3 帧）内重新生成，区域外钉在 E 的 x⁻ 上并羽化贴回"),
    "BVI": ("插入 · BVI（base 35 步，edge + vis）", "x⁻ 即 BV 的 x⁻；x⁺ 的 edge 同 EI，vis 来自贴了 CARLA 行人像素的 clean plate"),
}
ORDER = list(ARMS)


def existing_verdicts() -> dict:
    out, cur = {}, None
    if not DOC.exists():
        return out
    for line in DOC.read_text().splitlines():
        if line.startswith("### "):
            cur = line[4:].split("·")[0].strip() + "|" + line.split("`")[1] if "`" in line else None
        elif line.startswith(VERDICT) and cur:
            v = line[len(VERDICT):].strip()
            if v:
                out[cur] = v
    return out


def block(r: dict, verdict: str) -> list:
    title, setting = ARMS[r["arm"]]
    fi = r["frame_info"]
    s = f"x⁺ {r['s_plus']:.0f} s" if r["s_plus"] else "x⁺ —"
    if r["s_minus"]:
        s += f" + x⁻ {r['s_minus']:.0f} s"
    elif r["arm"] not in ("E", "Ed", "BV"):
        s += "（x⁻ 与移除对共用，不另算）"
    rows = [("场景", f"{r['key']} · WOD `{r['segment']}` · log 帧 {r['start']}–{r['start'] + 92}（10 Hz，9.3 s）· "
                     f"{fi.get('location', '?').replace('location_', '')}, {fi.get('time_of_day', '?')}, {fi.get('weather', '?')}"),
            ("设置", setting)]
    if r["ins"]:
        i = r["ins"]
        h = [x for x in i["h_px"] if x]
        rows.append(("插入的行人", f"CARLA `{i['src']}` 的行走序列（步态周期循环），1.5 m/s 从右侧路缘走向车道中心，第 80 帧到达车道中心；"
                                  f"可见第 {i['first']}–{i['last']} 帧，身高 {min(h)}–{max(h)} px" if h else "不可见"))
    else:
        rows.append(("目标行人", f"黄色轮廓（真实帧里）；≥ 300 px 的帧 {r['n_vis']} / 93，距离 {r['dist'][0]:.0f}–{r['dist'][1]:.0f} m；"
                                f"掩膜来源 YOLO {r['n_yolo']} 帧、投影框 {r['n_hull']} 帧"))
    rows += [("区域外 x⁺ / x⁻ 平均像素差", f"{r['out_diff']:.2f}（0–255，编辑区域膨胀 24 px 以外；只作参考）"),
             ("GPU 时间", s + "（GPU 2，与 GIMM 插帧任务共享）")]
    lines = [f"### {r['key']} · {title} `{r['arm']}`", "", f"![{r['key']} {r['arm']}](figs/cn_pair/{r['webp']})", "",
             "| | |", "|:--|:--|"] + [f"| {k} | {v} |" for k, v in rows]
    return lines + ["", f"{VERDICT} {verdict}", "", "---", ""]


def main():
    rows = json.loads((REPO / "research/results/cn_pair/pairs.json").read_text())
    rows.sort(key=lambda r: (ORDER.index(r["arm"]) >= ORDER.index("EI"), r["key"], ORDER.index(r["arm"])))
    ver = existing_verdicts()
    head = DOC.read_text().split(MARK)[0].rstrip() + "\n\n" + MARK + "\n\n"
    body, sec = [], None
    for r in rows:
        s = "插入对" if r["arm"] in ("EI", "EIGb", "BVI") else "移除对"
        if s != sec:
            body += [f"## 审阅：{s}", ""]
            sec = s
        body += block(r, ver.get(f"{r['key']}|{r['arm']}", ""))
    DOC.write_text(head + "\n".join(body).rstrip() + "\n")
    print(f"{len(rows)} items, {sum(r['kb'] for r in rows) / 1024:.1f} MB of clips")


if __name__ == "__main__":
    main()
